"""Render a course to PDF (outline + chapter content).

The PDF is generated server-side with reportlab Platypus. Output is a
clean, printable course handout — useful for archival, offline
reading, and as a marketing artefact (a school can hand the PDF to a
pastor as a sample of what the platform produces).

Scope of this first iteration:

* Title page with course title + brief description.
* Module + chapter outline (table of contents shape).
* Per-chapter section with chapter title and rendered text blocks
  (HTML stripped to plain prose for now — rich rendering follows in
  a later iteration if there's demand).

Out of scope (deliberate):

* Embedded images / videos / audio (would balloon file size).
* Quiz / assignment rendering (no test-paper format yet).
* Multi-locale switch (whoever fetches the PDF gets the source
  locale; the route honours ``Accept-Language`` so the picker is
  applied before content reaches this module).
"""

from __future__ import annotations

import io
from typing import TYPE_CHECKING

from app.core.sanitize import html_to_plain_text

if TYPE_CHECKING:
    from reportlab.lib.styles import ParagraphStyle

    from app.models.course import Course


def _to_plain_text(html: str | None) -> str:
    """Collapse HTML to clean prose for the PDF.

    One shared implementation in ``core.sanitize`` — the same job the
    verse card and the scripture comparison were each doing with their
    own copy of the same regex.
    """
    return html_to_plain_text(html)


def _build_styles() -> dict[str, ParagraphStyle]:
    # function-level: keeps reportlab (~100ms) out of serverless cold start
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

    base = getSampleStyleSheet()
    styles: dict[str, ParagraphStyle] = {}
    styles["title"] = ParagraphStyle(
        "EquipTitle",
        parent=base["Title"],
        fontName="Helvetica-Bold",
        fontSize=28,
        leading=34,
        alignment=1,  # TA_CENTER
        spaceAfter=12,
    )
    styles["subtitle"] = ParagraphStyle(
        "EquipSubtitle",
        parent=base["Italic"],
        fontSize=12,
        leading=16,
        alignment=1,
        spaceAfter=30,
    )
    styles["heading_module"] = ParagraphStyle(
        "ModuleHeading",
        parent=base["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        spaceBefore=18,
        spaceAfter=8,
    )
    styles["heading_chapter"] = ParagraphStyle(
        "ChapterHeading",
        parent=base["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        spaceBefore=12,
        spaceAfter=6,
    )
    styles["body"] = ParagraphStyle(
        "Body",
        parent=base["BodyText"],
        fontSize=11,
        leading=15,
        spaceAfter=6,
    )
    styles["toc_entry"] = ParagraphStyle(
        "TocEntry",
        parent=base["BodyText"],
        fontSize=11,
        leading=15,
        leftIndent=20,
    )
    styles["footer"] = ParagraphStyle(
        "Footer",
        parent=base["Italic"],
        fontSize=9,
        textColor=(0.5, 0.5, 0.5),
    )
    return styles


def render_course_pdf(course: Course) -> bytes:
    """Return the PDF bytes for the given hydrated course.

    Caller is responsible for hydrating the course's title /
    description / module-tree at the requested locale BEFORE handing
    it in. This function is pure layout — no DB access, no locale
    resolution, no permission checks.
    """
    # function-level: keeps reportlab (~100ms) out of serverless cold start
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.units import inch
    from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=LETTER,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        # The PDF metadata title, not a heading: a document with no
        # title at all confuses a file manager, and the brand is the one
        # word that reads the same in every language served.
        title=course.title or "Equip",
        author="Equip",
    )
    styles = _build_styles()
    story: list = []

    # Title page.
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph(course.title or "", styles["title"]))
    if course.description:
        story.append(Paragraph(_to_plain_text(course.description), styles["subtitle"]))
    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph("Generated by Equip", styles["footer"]))
    story.append(PageBreak())

    # Table of contents.
    story.append(Paragraph("Contents", styles["heading_module"]))
    modules = list(course.modules or [])
    for module in modules:
        story.append(Paragraph(module.title or "", styles["body"]))
        for chapter in module.chapters or []:
            story.append(
                Paragraph(
                    chapter.title or "",
                    styles["toc_entry"],
                )
            )
    story.append(PageBreak())

    # Module + chapter body.
    for module in modules:
        story.append(Paragraph(module.title or "", styles["heading_module"]))
        if module.description:
            story.append(Paragraph(_to_plain_text(module.description), styles["body"]))
        for chapter in module.chapters or []:
            story.append(Paragraph(chapter.title or "", styles["heading_chapter"]))
            # Render any text blocks the chapter carries. We sort by
            # ``order_index`` so the printed sequence matches the
            # student-facing chapter view.
            blocks = sorted(
                (b for b in (getattr(chapter, "blocks", None) or []) if getattr(b, "block_type", "") == "text"),
                key=lambda b: getattr(b, "order_index", 0),
            )
            for block in blocks:
                content = getattr(block, "content", None) or ""
                plain = _to_plain_text(content)
                if plain:
                    story.append(Paragraph(plain, styles["body"]))
        story.append(PageBreak())

    doc.build(story)
    pdf_bytes = buf.getvalue()
    buf.close()
    return pdf_bytes


__all__ = ["render_course_pdf"]
