-- Supabase migration: drop_unused_indexes
--
-- Supabase performance advisor flagged 21 indexes that have never
-- been used (``pg_stat_user_indexes.idx_scan = 0``). Each unused
-- index still pays the write-amplification cost (every INSERT /
-- UPDATE on the parent table re-indexes them) AND occupies disk for
-- no read benefit.
--
-- The list below was generated by the advisor on 2026-05-21 against
-- production traffic. Indexes that ARE on the hot path:
--   * ix_quiz_attempts_user_quiz / ix_quiz_attempts_user_id
--   * ix_enrollments_user_course_unique / ix_enrollments_user_id
--   * ix_chapter_progress_user_chapter_unique / ix_chapter_progress_user_id
-- ... are kept. Only the ones with idx_scan = 0 are dropped here.
--
-- If a new query path ever needs one of these back, recreating an
-- index is cheap (single ``CREATE INDEX CONCURRENTLY`` on a few MB of
-- data). The downside of leaving them is permanent, the downside of
-- dropping is recoverable -- so we drop and re-create on demand.
--
-- Excluded from the drop list:
--   * ix_quiz_answers_graded_at -- the teacher pending-answers query
--     uses this in its WHERE clause (graded_at IS NULL); advisor
--     marks it unused because the prod data set doesn't yet exercise
--     it, but the query plan would degrade to a seq scan on the
--     answers table once the corpus grows. Keep.
--   * ix_courses_search_vector -- backs the full-text catalog search
--     in courses.py; only the advisor's stats horizon is too short
--     to see it. Keep.

DROP INDEX IF EXISTS public.idx_announcements_created_at;
DROP INDEX IF EXISTS public.idx_cohorts_status;
DROP INDEX IF EXISTS public.idx_enrollments_cohort_id;
DROP INDEX IF EXISTS public.ix_enrollments_course_id;
DROP INDEX IF EXISTS public.ix_chapter_progress_chapter_id;
DROP INDEX IF EXISTS public.ix_certificates_status;
DROP INDEX IF EXISTS public.ix_announcements_course_id;
DROP INDEX IF EXISTS public.ix_audit_logs_resource_type;
DROP INDEX IF EXISTS public.ix_announcements_created_by;
DROP INDEX IF EXISTS public.ix_certificates_admin_approved_by;
DROP INDEX IF EXISTS public.ix_certificates_cohort_id;
DROP INDEX IF EXISTS public.ix_certificates_course_id;
DROP INDEX IF EXISTS public.ix_certificates_teacher_approved_by;
DROP INDEX IF EXISTS public.ix_chapter_progress_completed_by;
DROP INDEX IF EXISTS public.ix_student_grades_cohort_id;
DROP INDEX IF EXISTS public.ix_chapter_progress_completed;
DROP INDEX IF EXISTS public.ix_content_translations_pending;
DROP INDEX IF EXISTS public.ix_courses_status_created_at;
DROP INDEX IF EXISTS public.ix_courses_access_mode;
